spin_manifest_version = "1"
authors = ["bharattech <bharattech@protonmail.com>"]
description = "Rust India upcoming Events"
name = "serverless-events"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "serverless-events"
source = "target/wasm32-wasi/release/serverless-events.wasm"
allowed_http_hosts = ["https://www.meetup.com", "https://hasgeek.com", "https://lu.ma"]
key_value_stores = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "ui"
files = [ { source = "static", destination = "/" } ]
[component.trigger]
route = "/static/..."
